# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Educational Sauna
paginate:       5
paginate_path:  "/blogs/:num"
baseurl:        ""
url:            "https://regenchen.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Yuchen Jin
  url:          github.com/regenchen
  email:        

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/Regenchen/Regenchen.github.io

# Gems
gems:
  - jekyll-paginate
