# Setup
title:            Educational Sauna
tagline:          'A blog by Yuchen Jin'
description:      'A blog by Yuchen Jin'
url:              'https://regenchen.github.io'
permalink:        pretty
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Yuchen Jin'
  url:            github.com/jiaxigu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
